export enum Errorcodes
{
    INVALID_USERNAME = 0,
    INVALID_EMAIL = 1,
    INVALID_USERNAME_EMAIL = 2,
    PASSWORD_TOO_SMALL = 3,
    PASSWORDS_DONT_MATCH = 4,
    INVALID_PFP = 5,
    INVALID_CONTACT = 6,
    INVALID_PFP_CONTACT = 7,
    INVALID_ADDRESS = 8,
    INVALID_REGION = 9,
    INVALID_ADDRESS_REGION = 10
}